language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN=""

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - mirraim@gmail.com
    on_success: never # default: change
    on_failure: always # default: always